name: Mangoman Nutrition and Fitness
favicon: null
layout_spectrum: 0.74487
typography_spectrum: 0.74486
title: Nutrition and Fitness for Insulin Resistance and Diabetes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#001c50'
    - '#96997e'
    - '#2c5673'
    - '#623000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
