name: Mangoman Nutrition and Fitness
favicon: null
layout_spectrum: 0.74487
typography_spectrum: 0.74486
title: Nutrition and Fitness for Insulin Resistance and Diabetes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#942525'
    - '#d39317'
    - '#e1c4c4'
    - '#ffffff'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
