name: Mangoman Nutrition and Fitness
favicon: null
layout_spectrum: 0.031228916253894567
typography_spectrum: 0.4756598575040698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5058404998853803
  lightness: 0.14333864417858422
  saturation: 0.13349286373704672
  rhythmicContrast: 0.19104000856168568
purpose: []
